#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

#
#       set up source and object targets
#
source_files := $(call add_files_from_src,,'*.c')
source_files += $(call add_files_from_arch,,'*.c')
source_files += $(call add_files_from_board,,'*.c')

obj_files := $(addprefix $(ComponentBuildDir)/, $(source_files:%.c=%.o))

-include $(obj_files:.o=.d)

#
#       set up include paths
#

INCPATH += $(ComponentSrcDir)/DataModelBackEnd
INCPATH += $(CCSP_OPENSOURCE_DIR)/include/fcgi-2.4.0/include
INCPATH += $(CCSP_OPENSOURCE_DIR)/include/libxml2-2.7.7
INCPATH += $(CCSP_OPENSOURCE_DIR)/include/curl-7.28.1
INCPATH += $(CCSP_OPENSOURCE_DIR)/include/openssl
INCPATH += $(ComponentSrcDir)/include
INCPATH += $(call get_arch_or_board_src_path)
CFLAGS += $(addprefix -I, $(INCPATH))

#
#       set up linked libraries
#

LDFLAGS   += -lccsp_common
LDFLAGS   += -lsyscfg
LDFLAGS	 += -lcurl
LDFLAGS	 += -lxml2
LDFLAGS	 += -lulog


target := $(ComponentBuildDir)/CcspHomeSecurity

$(target) : $(obj_files)

#
#       set up targets
#

all: $(target) 

.PHONY: all clean install

clean:
	rm -Rf $(ComponentBuildDir)

install:
	@echo "Installing CcspHomeSecurity Installables"
	@-mkdir -p $(CCSP_OUT_DIR)
	@cp $(target) $(CCSP_OUT_DIR)


